FROM node:18.16.0-alpine
EXPOSE 6969
WORKDIR /app
COPY package.json package-lock.json ./
COPY n.04.bookingtour/BookingTour/package.json n.04.bookingtour/BookingTour/package-lock.json ./
COPY n.05-docker-mongo/package.json n.05-docker-mongo/package-lock.json ./
RUN npm install -g concurrently
COPY . .
RUN npm run watch
CMD [ "npm","start" ]